apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  af-api
  labels:
    name:  af-api
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:   af-api
    spec:
      containers:
      - image:  tabed23/atrial-fibrillation:latest
        name:   af-api
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        ports:
        - containerPort:  5000
          name:  my-name
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always
---


apiVersion: v1
kind: Service
metadata:
  name: Atrial-Fibrillation
spec:
  selector:
    app: af-api
  type:  NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  5000
