---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: af-api-deploy
  labels:
    app: af-api-app
    test: test
spec:
  selector:
    matchLabels:
      app: af-api-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: af-api-app
    spec:
      containers:
      - name: af-api-app
        image: tabed23/atrial-fibrillation:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
           httpGet:
             path: /health
             port: 5000
           initialDelaySeconds: 3
           periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      tolerations:
      - key: "cattle.io/os"
        value: "linux"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: af-api-deploy
spec:
  selector:
    app: af-api
  ports:
  - port: 5000
    targetPort: 5000

